モデル・バリデーション設定
Yasunori-aloha/PF_Summary_Website pull request #18
Opened 2021-01-12 14:01 UTC by yamamuro1138

## 概要
・各モデルのバリデーションの記述
・各マイグレーションファイルにカラムを追加し、テーブル作成
・意図した通りに正常に動いているか、各モデルをテストした

## 変更点
・各モデルファイルを生成し、アソシエーションやバリデーションを記述
・モデルファイル生成によって、作られたマイグレーションファイルにカラムを追加
・テーブル作成
・FactoryBotにそれぞれ値を定義し、Rspecにて単体テストコードを記述し実行した
## テスト結果とテスト項目
単体テストコード記述後に、各モデルが正常に動いているか確認

## lssue番号
#17 

https://gyazo.com/7f759e9052a10b657beb704099501f78
https://gyazo.com/2ade6814c494e9407114ac98ba06f12f
https://gyazo.com/759376ba720cebba9599eb4f41c7a7c2
https://gyazo.com/f507e0f37f5acfc4d98957935f21ab3a
https://gyazo.com/0f38510f23fc12821662915188186cae

2021-01-13 04:01 UTC, Yasunori-aloha requested changes
モデルのカラム名が全体的に日本語化されていないため、カラム名も全て日本語化して該当する箇所の記述も変更しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on README.md
> +https://i.gyazo.com/6218bf3293c5a2a8f0e543a08073d349.png
ここは画像へのリンクではなく、Slackでもお伝えした通りマークダウン記法で記述して画像がそのまま表示されるようにしましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/bookmark_spec.rb
> +  let(:bookmark) { FactoryBot.create(:bookmark, user_id: user.id, post_id: post.id) }
事前に`create`してしまうとbe_validで確認する必要がなくなってしまうので、`build`に変更しましょう。
また、`factory_bot`でアソシエーションを記述していれば外部キーは入力されますので`user_id`等の記述は省略してしまいましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/bookmark_spec.rb
> +        another_bookmark = FactoryBot.build(:bookmark, user_id: user.id, post_id: post.id)
同じ投稿・ユーザーの変数を作成するなら、`user.id`はその都度変更されてしまいますので既にsaveメソッド で保存されている`bookmark.user.id`等を使用しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/like_spec.rb
> +        another_like = FactoryBot.build(:like, user_id: user.id, post_id: post.id)
こちらも`user.id`はその都度変更されてしまいますので、`bookmark.user.id`等を使用しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/like_spec.rb
> +  let(:like) { FactoryBot.create(:like, user_id: user.id, post_id: post.id) }
こちらも、事前に`create`してしまうとbe_validで確認する必要がなくなってしまうので、`build`に変更しましょう。
また、`factory_bot`でアソシエーションを記述していれば外部キーは入力されますので`user_id`等の記述は省略してしまいましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/bookmark_spec.rb
> +    end
`存在しない投稿に対してのブックマーク`のテストコードも追加しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/like_spec.rb
> +    end
`存在しない投稿に対してのいいね`のテストコードも追加しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/bookmark_spec.rb
> +  describe 'いいね機能' do
`いいね機能`のテストコードになってしまっていますので、`ブックマーク機能`に変更しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/post_spec.rb
> +  let(:post) { FactoryBot.create(:post)}
こちらも、事前に`create`してしまうとbe_validで確認する必要がなくなってしまうので、`build`に変更しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/post_spec.rb
> +    end
`未ログインユーザーは投稿できない`というテストコードも追加しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/tag_spec.rb
> +  let(:tag) { FactoryBot.create(:tag) }
こちらも、事前に`create`してしまうとbe_validで確認する必要がなくなってしまうので、`build`に変更しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/user_spec.rb
> +  let(:another_user) { FactoryBot.create(:user) }
こちらも、事前に`create`してしまうとbe_validで確認する必要がなくなってしまうので、`build`に変更しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on spec/models/user_spec.rb
> +        expect(user.errors.full_messages).to include 'Password confirmationとPasswordの入力が一致しません'
エラーメッセージが全て`Password confirmationとPasswordの入力が一致しません`というのはテスト内容に合っていませんので、テスト内容にあうメッセージに変更しましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on app/models/user.rb
> +         with_options format: { with: /\A[a-zA-Z0-9]+\z/} do
この正規表現は`半角英数字が1文字以上`というバリデーションになってしまっていますので、`8文字以上で且つ半角英数字が最低1文字ずつ入っている`というバリデーションに変更しましよう。
また、バリデーションに引っかかった際にメッセージが表示されるようにしましょう。

2021-01-13 04:01 UTC, Yasunori-aloha commented on app/models/user.rb
> +          validates :password_confirmation
`password`にバリデーションをかけていれば、`password`と値が一致しなければ登録が弾かれるのでバリデーションから外してしまいましょう。
また、`password_confirmation`は現状何も入力がない場合にバリデーションに引っ掛からないので、バリデーションを設定しましょう。

2021-01-13 04:05 UTC, Yasunori-aloha reviewed
申し訳ありません。
見落としがありましたので、追加でコメントします。
確認をお願いします。

2021-01-13 04:05 UTC, Yasunori-aloha commented on app/models/user.rb
> +         has_many :bookmarks
ユーザーが削除された場合に、関連するレコードも削除されるように設定を記述しましょう。

2021-01-13 04:05 UTC, Yasunori-aloha commented on app/models/post.rb
> +  has_many :posts_tags
こちらも、投稿が削除されたら関連するレコードが削除されるように設定を記述しましょう。

2021-01-13 06:55 UTC, yamamuro1138 commented on README.md
> +https://i.gyazo.com/6218bf3293c5a2a8f0e543a08073d349.png
修正しました

2021-01-13 07:06 UTC, yamamuro1138 commented on spec/models/like_spec.rb
> +        another_like = FactoryBot.build(:like, user_id: user.id, post_id: post.id)
確認ですが、こちらはlike.user.idではなく
bookmark.user.idですか？

2021-01-13 07:14 UTC, yamamuro1138 commented on spec/models/bookmark_spec.rb
> +        another_bookmark = FactoryBot.build(:bookmark, user_id: user.id, post_id: post.id)
ユーザーの変数を固定にしました。

2021-01-13 07:15 UTC, yamamuro1138 commented on spec/models/like_spec.rb
> +        another_like = FactoryBot.build(:like, user_id: user.id, post_id: post.id)
ユーザーの変数を固定にしました。

2021-01-13 07:16 UTC, yamamuro1138 commented on spec/models/bookmark_spec.rb
> +  let(:bookmark) { FactoryBot.create(:bookmark, user_id: user.id, post_id: post.id) }
修正しました。

2021-01-13 07:23 UTC, yamamuro1138 commented on spec/models/like_spec.rb
> +  let(:like) { FactoryBot.create(:like, user_id: user.id, post_id: post.id) }
修正しました。

2021-01-13 07:27 UTC, yamamuro1138 commented on spec/models/bookmark_spec.rb
> +    end
追加しました

2021-01-13 07:28 UTC, yamamuro1138 commented on spec/models/like_spec.rb
> +    end
追加しました

2021-01-13 07:29 UTC, yamamuro1138 commented on spec/models/bookmark_spec.rb
> +  describe 'いいね機能' do
該当箇所もブックマークに変更しました

2021-01-13 07:32 UTC, yamamuro1138 commented on spec/models/post_spec.rb
> +  let(:post) { FactoryBot.create(:post)}
修正しました

2021-01-13 07:34 UTC, yamamuro1138 commented on spec/models/post_spec.rb
> +    end
追加しました

2021-01-13 07:35 UTC, yamamuro1138 commented on spec/models/tag_spec.rb
> +  let(:tag) { FactoryBot.create(:tag) }
修正しました

2021-01-13 07:37 UTC, yamamuro1138 commented on spec/models/user_spec.rb
> +  let(:another_user) { FactoryBot.create(:user) }
修正しました

2021-01-13 07:42 UTC, Yasunori-aloha commented on spec/models/like_spec.rb
> +        another_like = FactoryBot.build(:like, user_id: user.id, post_id: post.id)
申し訳ありません。
`bookmark.user.id`ではなく`like.user.id`ですね...

2021-01-13 13:13 UTC, yamamuro1138 commented
全て修正完了です。

2021-01-13 14:32 UTC, Yasunori-aloha requested changes
修正箇所確認しました。
何点かコメントしましたので、再度確認をお願いします。

2021-01-13 14:32 UTC, Yasunori-aloha commented on app/models/user.rb
> +         validates :password, confirmation: true
`confirmation: true`はパスワードの正規表現の後ろに移動させてしまいましょう。

また、確認用パスワードの空白が許可されているので、許可しないようにバリデーションを設定しましょう。

2021-01-13 14:32 UTC, Yasunori-aloha commented on spec/models/user_spec.rb
> +        expect(user.errors.full_messages).to include 'パスワード（確認）とパスワードの入力が一致しません'
確認用パスワードが空白の場合のエラーメッセージになっていないため、再度設定しましょう。

2021-01-13 14:32 UTC, Yasunori-aloha commented on app/models/user.rb
> +          validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,}+\z/i}
正規表現の最後の`+`はなくても成立するため、消してしまいましょう。

2021-01-14 06:59 UTC, yamamuro1138 commented
修正完了です。

2021-01-14 08:02 UTC, hatoya0703 commented on spec/factories/comments.rb
> +  factory :commnte do
お疲れさまです。
`commnte => comment`にスペルの修正お願いします。

2021-01-14 09:59 UTC, yamamuro1138 commented
修正しました

2021-01-14 10:11 UTC, hatoya0703 submitted a review, later dismissed
修正ありがとうございました、LGTMします！

2021-01-14 10:20 UTC, Yasunori-aloha approved these changes, later dismissed
修正箇所確認しました！
コメントした箇所はありますが、処理的には問題ありませんので、LGTMとさせていただきます！

2021-01-14 10:20 UTC, Yasunori-aloha commented on app/models/user.rb
> +         validates :password_confirmation, presence: true
細かいところですが、ここは`with_options`で括ってしまっても良いかもしれません。
ただ、2行だけですし処理的にも問題ありませんので、好みの問題かもしれません。

2021-01-14 11:36 UTC, hatoya0703 approved these changes
LGTMです！

2021-01-14 11:43 UTC, Yasunori-aloha approved these changes

2021-01-14 11:51 UTC, merged